# Use Node.js base image
FROM node:23.8-bullseye

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the app source code
COPY . .

# Expose the app port
EXPOSE 3000

# Run the application
CMD ["npm", "run", "dev"]
